//Comandos




#define oMODO_NORMAL 0xEE
#define oMODO_SINCRONIZACION 0xEF
#define oSONDEO_REMOTOS 0xDF

#define oAJUSTAR_FECHA 0x01
#define oAJUSTAR_HORA 0x02
#define oVOLVER_AJUSTES_FABRICA 0x03

#define oALTA_ELEMENTO 0x04

#define oACTIVAR_PERSIANA 0x05
#define oDESACTIVAR_PERSIANA 0x06
#define oDETENER_PERSIANA 0x07

#define oACTIVAR_LUZ_SIMPLE 0x08
#define oDESACTIVAR_LUZ_SIMPLE 0x09

#define oACTIVAR_LUZ_REGULADA 0x0A
#define oDESACTIVAR_LUZ_REGULADA 0x0B
#define oREGULAR_LUZ_REGULADA 0x0C

#define oACTIVAR_ENCHUFE 0x0D
#define oDESACTIVAR_ENCHUFE 0x0E

#define oAJUSTAR_CONSIGNA_DIA 0x10
#define oAJUSTAR_MAX_NOCHE 0x11
#define oAJUSTAR_MIN_NOCHE 0x12
#define oMODO_DIA 0x13
#define oMODO_NOCHE 0x14
#define oAJUSTAR_VELOCIDAD_VENT 0x15



#define oEJECUTAR_ESCENA 0x0F

#define oALTA_TARJETA 0x20

#define oALTA_TERMINAL_MONEDERO 0x40
#define oALTA_TARJETA_MONEDERO 0x41
#define oBAJA_TARJETA_MONEDERO 0x42
#define oCONSULTAR_SALDO_TARJETA_MONEDERO 0x43
#define oINCREMENTAR_SALDO_TARJETA_MONEDERO 0x44

